# nixpacks.toml

[provide.php]
version = "8.2" 

[build]
# Daftar perintah yang dijalankan saat proses build
# Menjalankan migrasi secara otomatis ada di sini
cmds = [
    "composer install --no-dev",
    "php artisan key:generate --force",
    "php artisan migrate --force"
]

[start]
# Perintah untuk menjalankan server setelah build berhasil
cmd = "php artisan serve --host 0.0.0.0 --port ${PORT}"